### ISSUE TITLE
Allow Null Portal

### ISSUE THREAD

**Issue by Log1x** [Multiverse/Multiverse-NetherPortals#105] opened 2015-08-22 08:34 UTC
```
[08:07:59] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to Multiverse-NetherPortals v2.5-b692
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.PlayerList.changeDimension(PlayerList.java:673) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.EntityPlayer.c(EntityPlayer.java:552) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.Entity.K(Entity.java:297) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:169) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:257) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1452) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:174) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:293) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:384) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: Cannot use null location!
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at org.bukkit.event.player.PlayerMoveEvent.validateLocation(PlayerMoveEvent.java:91) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at org.bukkit.event.player.PlayerMoveEvent.setTo(PlayerMoveEvent.java:86) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    at com.onarandombox.MultiverseNetherPortals.listeners.MVNPPlayerListener.onPlayerPortal(MVNPPlayerListener.java:90) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-25a137f-53fac9f]
    ... 23 more
```

Any possibility of allowing a null portal and getting this error to go away?

I have a Multiverse server with a Creative, Survival, Plot, Hub, and Minigames world. The only world(s) I want Multiverse-NetherPortals to interact with is Survival -> Nether and Nether -> Survival.

Every time someone goes through a portal in Hub powered by [Perfect Portal](https://www.spigotmc.org/resources/perfect-portal-bungee-portal-lot-of-features.6914/), that error is thrown.

I feel as if Multiverse-Portals shouldn't take over PlayerPortalEvent in world's that are not defined in it's config, nor should it expect there to be a defined value for every world no matter what. 

Maybe there were limitations here? If so, I guess disregard this ticket. But I'd LOVE for this to get fixed. I feel as if most bigger multi-world servers who don't want to use Bungee still using Multiverse will nowadays have a similar configuration.

Thanks a lot.

**Comment by Jadiction** [comment] 2019-06-20 05:15
Duplicate of https://github.com/Multiverse/Multiverse-NetherPortals/issues/104

**Closed by Jadiction** 2019-06-20 05:15 UTC
