### ISSUE TITLE
Players can't break portals

### ISSUE THREAD

**Issue by ZoefyC** [Multiverse/Multiverse-NetherPortals#122] opened 2017-01-21 19:44 UTC
Whenever a player breaks an obsidian block the portal doesn't get deactivated and an admin has to go and break the purple goo stuff.  Am I doing something wrong or is this a known issue? Please help :) #

**Comment by ZoefyC** [comment] 2017-02-07 12:18
Anyone? No? Ok. :(

**Comment by Jadiction** [comment] 2019-06-20 06:19
Can't reproduce. Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.

**Closed by Jadiction** 2019-06-20 06:19 UTC
