### ISSUE TITLE
Hostile Mobs Won't Go Through Portals

### ISSUE THREAD

**Issue by Munchkinnibbler** [Multiverse/Multiverse-NetherPortals#233] opened 2021-07-18 17:43 UTC
Hi, a server I assist on is having an issue with nether portals in that passive mobs & items can pass through portals however hostile mobs just vanish. 
The config is set up as follows:
bounceback: true
teleport_entities: true
send_no_destination_message: true
send_disabled_portal_message: true
worlds:
  testing_world:
    portalgoesto:
      NETHER: testing_world_hell
  testing_world_hell:
    portalgoesto:
      NETHER: testing_world
  HermitVeterans:
    portalgoesto:
      NETHER: hermitveterans_netherworld
  hermitveterans_netherworld:
    portalgoesto:
      NETHER: HermitVeterans
 The server is running on Purpur 1171 (the latest and last 1.16.5 version) and so I believe it will be using a 1.16.5 version of multiverse portals. I've tried asking around but no solution has been found, is there anything that would fix it?

**Comment by Waterman1001** [comment] 2021-07-19 16:53
I feel like this relates to my issue as well: See #230 
It would be nice if someone could try to resolve this issue :)

**Comment by Munchkinnibbler** [comment] 2021-07-23 11:56
> It would be nice if someone could try to resolve this issue :)
Indeed it would

**Comment by Munchkinnibbler** [comment] 2021-07-23 11:58
#230 Does seem related to this only in 1.16.5 so to hazard a guess it's been there for a while.

**Comment by zax71** [comment] 2024-08-23 11:40
I just tested this, and I can push hostile mobs through nether portals in 1.21

**Comment by zax71** [comment] 2024-12-02 22:04
Closing as no new info and cannot reproduce.

**Closed by zax71** 2024-12-02 22:04 UTC
Labels: Bug: Can't Reproduce
