### ISSUE TITLE
Items won't go thru Nether Portals.

### ISSUE THREAD

**Issue by smartn1nja** [Multiverse/Multiverse-NetherPortals#97] opened 2014-06-10 20:19 UTC
Items won't go thru Nether Portals. This only happens to worlds that are not "world" and "world_nether". Obviously Multiverse-NetherPortals bug please fix ASAP :)

**Comment by gabessdsp** [comment] 2016-01-25 20:13
Or obviously it's your problem for not using a world-inventories plugin. Use Multiverse-Inventories or Multiinv

**Comment by dali99** [comment] 2016-02-03 21:13
I think this is probably a duplicate of #72

**Comment by Jadiction** [comment] 2019-06-20 03:10
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.

**Closed by Jadiction** 2019-06-20 03:10 UTC
