### ISSUE TITLE
Strange issue with end portal

### ISSUE THREAD

**Issue by CoolLord22** [Multiverse/Multiverse-NetherPortals#123] opened 2017-03-16 00:24 UTC
If you use end portals for a world that doesn't have an end setup, this message gets spammed like crazy in console and the player just glitches on the dirt screen (like the empty background)

http://pastebin.com/UFJ291Mi

**Comment by CoolLord22** [comment] 2017-10-14 17:12
This was fixed by https://github.com/Multiverse/Multiverse-NetherPortals/pull/117 but in the latest dev build the issue returned (https://ci.onarandombox.com/job/Multiverse-NetherPortals/) any word on if this will be fixed? @FernFerret / @dumptruckman

**Comment by Jadiction** [comment] 2019-06-20 05:16
Duplicate of https://github.com/Multiverse/Multiverse-NetherPortals/issues/104

**Closed by Jadiction** 2019-06-20 05:16 UTC
