### ISSUE TITLE
Separate Nether Portals in Overworld Linking to same Nether Portal

### ISSUE THREAD

**Issue by CainSeldon** [Multiverse/Multiverse-NetherPortals#109] opened 2016-03-14 17:00 UTC
As the subject says, I have different nether portals in the Overworld, however they are all linking to the same portal in the nether rather than creating different portals using the world scaling feature. Also returning from the nether puts the player at the portal at spawn rather than the one you walked through ( The portal at spawn was the first portal i used to test this). The reason i installed this plugin was to make use of this feature; I want my players to be able to build their own nether portals so they can go to the nether and it spawn them in their own locations.

Might be worth mentioning that upon installation, the portals would not function at all, I had to manually link the Overworld with the nether to get them to even work. 

What do I do at this point to allow the functionality I am looking for? Thanks guys!

**Comment by FernFerret** [comment] 2016-03-16 03:19
I don't have time right now to look into this, but some quick suggestions to test: there is a config variable, `searchradius` maybe try lowering that? If you lower it, portals will be more discreet and less... fuzzy, meaning the numbers will correlate more specifically.

Maybe I read your question wrong, but feel free to reply with some additional details. We're here, just don't have time to try this out right now.

One thing that would help us a ton is a simple set of steps to reproduce, as detailed as possible would be good.

**Comment by Sketched360** [comment] 2017-12-21 16:27
Have you guys found a solution to this problem? I'm having the same problem as well

**Comment by Jadiction** [comment] 2019-06-20 05:22
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.

**Closed by Jadiction** 2019-06-20 05:22 UTC

**Comment by dirkniblick** [comment] 2020-07-18 18:12
This is *not* an old issue. I am running the "newest" Multiverse plugins on a paper 1.16.1, build 98 and all nether portals created in the "overworld" go to the same portal in the linked nether world. Doesn't matter where you create the portal in the overworld.

**Comment by Jadiction** [comment] 2020-07-19 07:36
@dirkniblick 
Read the comment again. It says it's an old post, not an old issue. Then there's this:
`otherwise please don't hesitate to ask for support on our Discord (quickest support) or submit a new issue.`

**Comment by dirkniblick** [comment] 2020-07-19 17:28
@Jadiction, thanks for the unhelpful yet passive aggressive comment. 😝

For *others* who might have this problem, when you create a nether or end world with Multiverse (`mvcreate World nether`), it doesn’t configure the `scale` property correctly. They should have scale values of 8 and 16, respectively, rather than 1, which makes traveling through either of these types of worlds move you further around than in the “normal” world. You can fix the scale with `mvmset scale 8`. After we did this, nether portals worked like they should.

There *is* a `portal-search-radius` in the server I use, PaperMC, which one could reduce but, again, it’s not necessary if the world’s scale is configured correctly.
