### ISSUE TITLE
Nether Portal to TP entities

### ISSUE THREAD

**Issue by SmexyDuk** [Multiverse/Multiverse-NetherPortals#154] opened 2020-05-01 02:51 UTC
Is it possible to use this plugin to transport entities to for example, Nether? That'll be nice thank you. I hoep someone can help me out.

**Comment by Brenyku** [comment] 2020-05-14 07:03
I'm having the same issue, could this be fixed please?

**Comment by nicegamer7** [comment] 2020-05-14 07:20
Duplicate of #72.

**Closed by nicegamer7** 2020-05-14 07:20 UTC
