### ISSUE TITLE
[1.16.2] Portals crashes the server.

### ISSUE THREAD

**Issue by Speak2Erase** [Multiverse/Multiverse-NetherPortals#174] opened 2020-08-23 19:59 UTC
I'm trying to set up a server using multiverse to manage a few of my worlds, so I can have a creative world, a survival world, and a super flat world under one server.
I went ahead and linked up all the worlds with their nether and end equivalents, and whenever I enter a portal, the server crashes. My guess is it has to do with 1.16 changing the dimensions are handeled. allow nether and allow end is enabled in bukkit.yml and server properties.
I'm not too good with debugging bukkit plugins (I can just about figure out how to fix most of the issues I encounter) but this one is beyond my capabilities.

[crash-2020-08-23_12.35.25-server.txt](https://github.com/Multiverse/Multiverse-NetherPortals/files/5114822/crash-2020-08-23_12.35.25-server.txt)

**Comment by tlrichar** [comment] 2020-08-24 02:08
Documented previously [here](https://github.com/Multiverse/Multiverse-Core/issues/2383). I think these are related, or this one is a duplicate of the other.

**Comment by Speak2Erase** [comment] 2020-08-24 02:13
Both are duplicates stemming from the same problem but in different scenarios.

**Comment by benwoo1110** [comment] 2020-10-05 03:10
Should be fixed by the latest papermc with reference to this [patch](https://github.com/PaperMC/Paper/blob/44e822f7cfd46d8dfbe9f0285ee41191b496295f/Spigot-Server-Patches/0578-Fix-block-data-exception-when-cancelling-PortalCreat.patch).

**Closed by benwoo1110** 2020-10-05 03:10 UTC
